name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  
    inputs:
      version:
        description: 'Provide the version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  

      - name: Install Maven
        run: sudo apt-get install maven -y

      - name: Build with Maven
        run: mvn clean install

      - name: Create Versioned War
        run: |
          VERSION=${{ github.event.inputs.version }}
          mkdir -p /mnt/target
          cp -r target/LoginWebApp.war /mnt
          mv /mnt/LoginWebApp.war /mnt/target/${VERSION}

